### ISSUE TITLE
Refactor Makefile

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-chailove#221]
@webgeek1234 I've seen you refactor the Makefiles across a lot of the cores. Are you up for a challenge with this one??? :smile: 

I haven't been able to get the Android compiler working here, so haven't touched the jni Makefile at all.

**Comment by webgeek1234** [comment]
Once I finish the existing android cores, the plan is to look through the rest and get as many of them going as I can. So yeah, I'll try within a few days. There's no technical reason this wouldn't run, right?

**Comment by RobLoach** [comment]
Thanks! Been loving those updates, it cleans up the Makefiles so much. Technical hurdle may be the dependency chain. The problematic libraries have been...

- C++14
- SDL
- FreeType2
- zlib

Currently compiles for MacOSX, ARM, Windows and Linux, so I'm sure Android should be okay too. Just needs some Makefile-jitsu.

**Comment by webgeek1234** [comment]
https://github.com/webgeek1234/libretro-chailove/commit/67adf09818427dec7d5320f7d41e861a2d33846d

Well, it compiles. Requires clang/libc++ for the c++14 stuff, though. Also seems to be a bug in NDK r15c, the 32 bit platforms failed, but they all compile on r16b fine, so it'll at least have to wait until I push everything to r16b, but that won't be long. I can't test that it actually works until tonight, though. I'll need the docs on how that works.

Since I did have to touch the common make file, can you pull the commit and make sure I didn't break any other platform/arch?

**Comment by RobLoach** [comment]
It's looking great! Tests passing on Linux and MacOSX, trying to get Appveyor up to test Windows. Thanks a lot for fixing this up. Looks a lot nicer now.

**Comment by RobLoach** [comment]
Seeing the linker error with 15...
https://github.com/android-ndk/ndk/issues/502

**Comment by webgeek1234** [comment]
I did mention that yesterday, and that's mainly why I didn't PR it myself then...

I'm going to switch all the jni builds over to r16b soon, but probably not for a week or so. The cmake recipes are already using it. I guess for the moment, this core will only have 64-bit builds on Android. Which... Isn't particularly user facing since arm64 requires a different retroarch apk and x86_64 isn't built at all.

**Comment by RobLoach** [comment]
Made a note about buildbot in the [0.19.0 release notes](https://github.com/libretro/libretro-chailove/releases/tag/0.19.0). It compiles, just not compiling with Buildbot yet. :+1:

**Comment by RobLoach** [comment]
Just tested on Android and it worked well! Nicely done, @webgeek1234 ... Thanks so much for making this happen.

![floppy bird-180424-231738](https://user-images.githubusercontent.com/25086/39242276-8586c77a-4857-11e8-9b40-24c9dabc44d4.png)
